### PR TITLE
internal/rule: fix squashjoins rule to squash projections properly too

### LINKED ISSUE #322: error using natural joins
```
mysql> SELECT count(1), refs.repository_id FROM refs NATURAL JOIN commits NATURAL JOIN commit_blobs WHERE refs.ref_name = 'HEAD' GROUP BY refs.repository_id;
ERROR 1105 (HY000): unknown error: unable to find field with index 14 in row of 12 columns
```

### PR DESCRIPTION
**Pull request by mcarmonaa**
Fixes #322 

The bug came because the projects nodes over inner joins weren't squashed, so they stayed chained and pointing to wrong field indexes after the table squashing
```
GroupBy
 ├─ Aggregate(COUNT(1), refs.repository_id)
 ├─ Grouping(refs.repository_id)
 └─ Project(refs.repository_id, refs.commit_hash, refs.ref_name, commits.commit_author_name, commits.commit_author_email, commits.commit_author_when, commits.committer_name, commits.committer_email, commits.committer_when, commits.commit_message, commits.tree_hash, commits.commit_parents, commit_blobs.blob_hash)
     └─ Project(refs.repository_id, refs.commit_hash, refs.ref_name, commits.commit_author_name, commits.commit_author_email, commits.commit_author_when, commits.committer_name, commits.committer_email, commits.committer_when, commits.commit_message, commits.tree_hash, commits.commit_parents)
         └─ Filter(refs.repository_id = commit_blobs.repository_id AND refs.commit_hash = commit_blobs.commit_hash)
             └─ SquashedTable(refs, commits, commit_blobs)
                 ├─ Columns
                 │   ├─ Column(repository_id, TEXT, nullable=false)
                 │   ├─ Column(ref_name, TEXT, nullable=false)
                 │   ├─ Column(commit_hash, TEXT, nullable=false)
                 │   ├─ Column(repository_id, TEXT, nullable=false)
                 │   ├─ Column(commit_hash, TEXT, nullable=false)
                 │   ├─ Column(commit_author_name, TEXT, nullable=false)
                 │   ├─ Column(commit_author_email, TEXT, nullable=false)
                 │   ├─ Column(commit_author_when, TIMESTAMP, nullable=false)
                 │   ├─ Column(committer_name, TEXT, nullable=false)
                 │   ├─ Column(committer_email, TEXT, nullable=false)
                 │   ├─ Column(committer_when, TIMESTAMP, nullable=false)
                 │   ├─ Column(commit_message, TEXT, nullable=false)
                 │   ├─ Column(tree_hash, TEXT, nullable=false)
                 │   ├─ Column(commit_parents, JSON, nullable=false)
                 │   ├─ Column(repository_id, TEXT, nullable=false)
                 │   ├─ Column(commit_hash, TEXT, nullable=false)
                 │   └─ Column(blob_hash, TEXT, nullable=false)
                 └─ Filters
                     ├─ refs.repository_id = commit_blobs.repository_id
                     ├─ refs.commit_hash = commit_blobs.commit_hash
                     ├─ refs.repository_id = commits.repository_id
                     ├─ refs.commit_hash = commits.commit_hash
                     └─ refs.ref_name = "HEAD"

```

Now the project nodes are squashed too, so it works properly:
```
GroupBy
 ├─ Aggregate(COUNT(1), refs.repository_id)
 ├─ Grouping(refs.repository_id)
 └─ Project(refs.repository_id, refs.commit_hash, refs.ref_name, commits.commit_author_name, commits.commit_author_email, commits.commit_author_when, commits.committer_name, commits.committer_email, commits.committer_when, commits.commit_message, commits.tree_hash, commits.commit_parents, commit_blobs.blob_hash)
     └─ Filter(refs.repository_id = commit_blobs.repository_id AND refs.commit_hash = commit_blobs.commit_hash)
         └─ SquashedTable(refs, commits, commit_blobs)
             ├─ Columns
             │   ├─ Column(repository_id, TEXT, nullable=false)
             │   ├─ Column(ref_name, TEXT, nullable=false)
             │   ├─ Column(commit_hash, TEXT, nullable=false)
             │   ├─ Column(repository_id, TEXT, nullable=false)
             │   ├─ Column(commit_hash, TEXT, nullable=false)
             │   ├─ Column(commit_author_name, TEXT, nullable=false)
             │   ├─ Column(commit_author_email, TEXT, nullable=false)
             │   ├─ Column(commit_author_when, TIMESTAMP, nullable=false)
             │   ├─ Column(committer_name, TEXT, nullable=false)
             │   ├─ Column(committer_email, TEXT, nullable=false)
             │   ├─ Column(committer_when, TIMESTAMP, nullable=false)
             │   ├─ Column(commit_message, TEXT, nullable=false)
             │   ├─ Column(tree_hash, TEXT, nullable=false)
             │   ├─ Column(commit_parents, JSON, nullable=false)
             │   ├─ Column(repository_id, TEXT, nullable=false)
             │   ├─ Column(commit_hash, TEXT, nullable=false)
             │   └─ Column(blob_hash, TEXT, nullable=false)
             └─ Filters
                 ├─ refs.repository_id = commit_blobs.repository_id
                 ├─ refs.commit_hash = commit_blobs.commit_hash
                 ├─ refs.repository_id = commits.repository_id
                 ├─ refs.commit_hash = commits.commit_hash
                 └─ refs.ref_name = "HEAD"

```

Signed-off-by: Manuel Carmona <manu.carmona90@gmail.com>

### CODE REVIEW

File: internal/rule/squashjoins.go [hunk 1]
```diff
@@ -39,18 +42,103 @@ func SquashJoins(
...
+	return squashableProjects - 1
+}
+
+// ErrWrongProjection is raised if a plan.Project node contains a wrong expression.
+var ErrWrongProjection = errors.NewKind("wrong expression found in project node %s")
+
+func squashProjects(parent, child *plan.Project) (sql.Node, error) {
+	projections := []sql.Expression{}
+	for _, expr := range parent.Expressions() {
+		parentField, ok := expr.(*expression.GetField)
```
Comment (ajnavarro) [inline internal/rule/squashjoins.go]: If an expression is a literal, this will fail? Example: 
```
SELECT count(1),1 , refs.repository_id
FROM refs
NATURAL JOIN commits
NATURAL JOIN commit_blobs
WHERE refs.ref_name = 'HEAD'
GROUP BY refs.repository_id
```

Comment (mcarmonaa) [reply internal/rule/squashjoins.go]: That query doesn't work because of how the `GroupBy` is implemented right now. It only allows expressions in the select which are aggregations or are in the group by too, not because of the changes in this PR.

The following query, for example. does work:
```
MySQL [(none)]> SELECT 1,refs.repository_id FROM refs NATURAL JOIN commits NATURAL JOIN commit_blobs WHERE refs.ref_name = 'HEAD' limit 10;
+------+---------------+
| 1    | repository_id |
+------+---------------+
|    1 | enry          |
|    1 | enry          |
|    1 | enry          |
|    1 | enry          |
|    1 | enry          |
|    1 | enry          |
|    1 | enry          |
|    1 | enry          |
|    1 | enry          |
|    1 | enry          |
+------+---------------+
10 rows in set (0.02 sec)

```

Comment (ajnavarro) [reply internal/rule/squashjoins.go]: then, how can we reach that error?

Comment (mcarmonaa) [reply internal/rule/squashjoins.go]: Sorry @ajnavarro, I think I'm not understanding you. Do you mean that if a literal appears in the projection the query should fail? Anyway that's something not related to this PR, I guess.

Should I open an issue for it?

Comment (ajnavarro) [reply internal/rule/squashjoins.go]: I'm trying to understand when this error will be thrown. 

As I can see on the `squashProjects` you are getting the expressions on the projection and checking if the type is a `Getfield` expression. If not, you are throwing an error.

There are some cases when a projection can contain other expressions than `GetField` (per example, a `Function` or a `Literal`), and that is not necessarily an error.

Comment (mcarmonaa) [reply internal/rule/squashjoins.go]: :nerd_face: Now I see what you mean. The thing is that the projections to squash coming from the replacement of natural joins by inner joins, and those projections only contains `GetFields`. That's the reason because the chained projections appear, so functions and literals written in a query aren't going to be squashed.

**Comment by mcarmonaa** [comment]
@ajnavarro I already committed the change to not throw an error

File: internal/rule/squashjoins.go [hunk 2]
```diff
@@ -39,18 +42,103 @@ func SquashJoins(
...
+			return n, nil
+		}
+
+		child, ok := project.Child.(*plan.Project)
+		if !ok {
+			return n, nil
+		}
+
+		squashedProject, err := squashProjects(project, child)
+		if err != nil {
```
Comment (ajnavarro) [inline internal/rule/squashjoins.go]: Other error than errWrongProjection can happen.

Comment (ajnavarro) [reply internal/rule/squashjoins.go]: Actually, cannot, but this code is a little bit misleading. Maybe instead of return squashedProject and err we should return squasedProject and ok

Comment (mcarmonaa) [reply internal/rule/squashjoins.go]: Done
