### PR TITLE
gitbase: report repository id on errors

### LINKED ISSUE #909: Report repository_id on errors
When a query fails because of a git error, like the infamous `object not found` or possibly other deeper I/O errors, it would be very helpful for troubleshooting if repository_id (or path or any other proxy) was added to the error.

### PR DESCRIPTION
**Pull request by erizocosmico**
Closes #909 

I started implementing this in another way, just wrapping error by error with the error to just do it on git errors, but it was a ton of changes and very prone to not be done in the future.

This way, the iterator is wrapped and the errores are always added the info, no matter how much we change the iterators and the errors they return.

 - [x] I updated the documentation explaining the new behavior if any.
 - [x] I updated CHANGELOG.md file adding the new feature or bug fix.
 - [x] I updated go-mysql-server using `make upgrade` command if applicable.
 - [x] I added or updated examples if applicable.
 - [x] I checked that changes on schema are reflected into the documentation, if applicable.

### CODE REVIEW

File: partition.go [hunk 1]
```diff
@@ -271,3 +271,36 @@ func (i *partitionedIndexKeyValueIter) Close() error {
...
+	iter sql.RowIter
+	repo *Repository
+}
+
+func newRepoRowIter(repo *Repository, iter sql.RowIter) sql.RowIter {
+	return &repoRowIter{iter, repo}
+}
+
+func (i *repoRowIter) Next() (sql.Row, error) {
+	row, err := i.Next()
```
Comment (golangcibot) [inline partition.go]: SA5007: infinite recursive call (from `staticcheck`)

**Comment by kuba--** [comment]
LGTM - what do you think about renaming to sth. like `errorWithRepo(...)`

**Comment by erizocosmico** [comment]
Done
