### PR TITLE
function: log bblfsh errors on UAST instead of returning them

### LINKED ISSUE #444: unexpected crash
The following request is being ran on top of the Go repo.

```sql
SELECT f.repository_id, f.file_path,
       LANGUAGE(f.file_path, f.blob_content) AS lang, f.blob_content,
       UAST(f.blob_content, LANGUAGE(f.file_path, f.blob_content)) AS uast
FROM   files AS f
       JOIN commit_files cf ON
            f.repository_id=cf.repository_id AND
            f.file_path=cf.file_path AND
            f.blob_hash=cf.blob_hash AND
            f.tree_hash=cf.tree_hash
       JOIN refs ON
            cf.repository_id = 'go' AND
            refs.repository_id = 'go' AND
            cf.commit_hash = refs.commit_hash
WHERE  ref_name = 'HEAD'
       AND f.file_path REGEXP('.*\.go')
```

After a dozen of seconds I just see the error `unknown error: rpc error: code = Unavailable desc = transport is closing` both in `gitbase-web`, `engine`, and `mysql`.

The logs of the container do not indicate any issue.

<details><code><pre>
23:54 ~ ➜  docker logs srcd-cli-gitbase
time="2018-08-28T05:53:54Z" level=debug msg="git repositories directory added" dir=/opt/repos
time="2018-08-28T05:53:54Z" level=debug msg="repository added" path=/opt/repos/go
time="2018-08-28T05:53:54Z" level=debug msg="registered database to catalog" db=
time="2018-08-28T05:53:54Z" level=debug msg="registered all available functions in catalog"
time="2018-08-28T05:53:54Z" level=debug msg="created index storage"
time="2018-08-28T05:53:54Z" level=debug msg="established connection with pilosa"
time="2018-08-28T05:53:54Z" level=debug msg="registered pilosa index driver"
time="2018-08-28T05:53:54Z" level=info msg="squash tables rule is enabled"
time="2018-08-28T05:53:54Z" level=info msg="server started and listening on 0.0.0.0:3306"
time="2018-08-28T05:53:59Z" level=info msg="NewConnection: client 1"
time="2018-08-28T05:53:59Z" level=debug msg="executing query" query="SHOW TABLES"
time="2018-08-28T05:53:59Z" level=debug msg="executing query" query="DESCRIBE TABLE remotes"
time="2018-08-28T05:53:59Z" level=debug msg="executing query" query="DESCRIBE TABLE tree_entries"
time="2018-08-28T05:53:59Z" level=debug msg="executing query" query="DESCRIBE TABLE commit_blobs"
time="2018-08-28T05:53:59Z" level=debug msg="executing query" query="DESCRIBE TABLE commit_trees"
time="2018-08-28T05:53:59Z" level=debug msg="executing query" query="DESCRIBE TABLE refs"
time="2018-08-28T05:53:59Z" level=debug msg="executing query" query="DESCRIBE TABLE files"
time="2018-08-28T05:53:59Z" level=debug msg="executing query" query="DESCRIBE TABLE ref_commits"
time="2018-08-28T05:53:59Z" level=debug msg="executing query" query="DESCRIBE TABLE repositories"
time="2018-08-28T05:53:59Z" level=debug msg="executing query" query="DESCRIBE TABLE blobs"
time="2018-08-28T05:53:59Z" level=debug msg="executing query" query="DESCRIBE TABLE commit_files"
time="2018-08-28T05:53:59Z" level=debug msg="executing query" query="DESCRIBE TABLE commits"
time="2018-08-28T05:54:04Z" level=debug msg="executing query" query="SELECT f.repository_id, f.file_path,\n       LANGUAGE(f.file_path, f.blob_content) AS lang, f.blob_content,\n       UAST(f.blob_content, LANGUAGE(f.file_path, f.blob_content)) AS uast\nFROM   files AS f\n       JOIN commit_files cf ON\n            f.repository_id=cf.repository_id AND\n            f.file_path=cf.file_path AND\n            f.blob_hash=cf.blob_hash AND\n            f.tree_hash=cf.tree_hash\n       JOIN refs ON\n            cf.repository_id = 'go' AND\n            refs.repository_id = 'go' AND\n            cf.commit_hash = refs.commit_hash\nWHERE  ref_name = 'HEAD'\n       AND f.file_path REGEXP('.*\\.go') LIMIT 100"
</pre></code></details>

### PR DESCRIPTION
**Pull request by erizocosmico**
Fixes #444 

I have been trying for a while but I can't seem to reproduce the original error (which is normal, considering it's a bblfsh error and there be dragons).

Anyway, as said in the issue, the UDF should not fail, so now all errors are logged but not returned and nil is returned instead.

### CODE REVIEW

**Comment by jfontan** [comment]
I've managed to reproduce the bblfsh error killing the driver process while it's processing. If you are using linux you can see the process with `ps`.

**Comment by erizocosmico** [comment]
ping @src-d/data-retrieval

**Comment by erizocosmico** [comment]
Rebased

File: internal/function/uast.go [hunk 1]
```diff
@@ -206,7 +207,8 @@ func (u *uastFunc) getUAST(
 				return nil, nil
 			}
 
-			return nil, err
+			logrus.WithField("err", err).Error("unable to get UAST from bblfsh")
+			return nil, nil
```
Comment (mcarmonaa) [inline internal/function/uast.go]: if we are not going to return an error,  the previous `if ErrParseBlob.Is(err)` is not necessary anymore

Comment (erizocosmico) [reply internal/function/uast.go]: It's there to not pollute the logs with infinite "can't parse"s

Comment (mcarmonaa) [reply internal/function/uast.go]: Then, what should be inside an `if` is the logging line maybe.
