### PR TITLE
internal/function: make UAST be able to use language results

### LINKED ISSUE #240: Error on uast functions
In fact, I believe it's a bug in bbflshd.

Trying to get the UAST:
```
MySQL [(none)]> select hash,name,language(name,content) as lang from blobs inner join tree_entries on blobs.hash = tree_entries.entry_hash limit 10;
+------+------+------+
| hash | name | lang |
+------+------+------+
| 314cce26042c27e70ba93c9f908ac266604b9c5b | adapters/adapter_skeleton.rb | Ruby |
| 0fe787e04b5e34d142fd797118139e0306a2de53 | adapters/ado.rb | Ruby |
| f49f2ad72362537f1a3709a16656f7250d598320 | adapters/db2.rb | Ruby |
| 1dc83307236316224155f00cbc9d87bceed12dda | adapters/dbi.rb | Ruby |
| 17d2f8dcae46da81310773a097ebee8398c630ae | adapters/informix.rb | Ruby |
| ae1d9ecbe2f5d451ddcbf8d4ac999883d3ef74ef | adapters/jdbc.rb | Ruby |
| fee027d38594c12fd6bdc440c6ab40c8bf5e86ec | adapters/mysql.rb | Ruby |
| 1d67bcd33c377cf6e377f0a5bc2b977a8f141ab7 | adapters/odbc.rb | Ruby |
| 30de1fba89315831ff57f3ac74daa587ec77cd74 | adapters/odbc_mssql.rb | Ruby |
| e7f941bec6266f1d7b01e2bdebc6b56c2b1ab14c | adapters/openbase.rb | Ruby |

MySQL [(none)]> select hash,name,language(name,content),uast(hash,language(name,content)) from blobs inner join tree_entries on blobs.hash = tree_entries.entry_hash limit 10;
ERROR 1105 (HY000): unknown error: unable to parse the given blob using bblfsh: unexpected error: runtime failure: missing driver for language "Ruby"

```
The bblfshd fails with error:
```
docker run --rm --name bblfshd --privileged -p 9432:9432 -v /var/lib/bblfshd:/var/lib/bblfshd bblfsh/bblfshd:v2.4.2
time="2018-04-17T13:03:17Z" level=info msg="bblfshd version: v2.4.2 (build: 2018-03-13T15:34:28+0000)"
time="2018-04-17T13:03:17Z" level=info msg="initializing runtime at /var/lib/bblfshd"
time="2018-04-17T13:03:17Z" level=info msg="server listening in 0.0.0.0:9432 (tcp)"
time="2018-04-17T13:03:17Z" level=info msg="control server listening in /var/run/bblfshctl.sock (unix)"
time="2018-04-17T13:03:29Z" level=error msg="error selecting pool: unexpected error: runtime failure: missing driver for language "Ruby""
time="2018-04-17T13:03:29Z" level=error msg="request processed content 40 bytes, status Fatal" elapsed=959.673µs filename= language=Ruby

docker exec -it bblfshd bblfshctl driver list
+------------+------------------------------------------+-------------+--------+----------+--------+-----+-------------+
|  LANGUAGE  |                  IMAGE                   |   VERSION   | STATUS | CREATED  |   OS   | GO  |   NATIVE    |
+------------+------------------------------------------+-------------+--------+----------+--------+-----+-------------+
| python     | docker://bblfsh/python-driver:latest     | dev-5df023e | beta   | 6 months | alpine | 1.8 | 3.6.2       |
| java       | docker://bblfsh/java-driver:latest       | dev-4a015eb | alpha  | 6 months | alpine | 1.8 | 8.131.11-r2 |
| javascript | docker://bblfsh/javascript-driver:latest | dev-adcd1b4 | beta   | 4 weeks  | alpine | 1.9 | 8.9.3-r0    |
| ruby       | docker://bblfsh/ruby-driver:latest       | dev-4b8a82b | beta   | 12 days  | alpine | 1.9 | 2.4.4-r0    |
| go         | docker://bblfsh/go-driver:latest         | dev-082d595 | beta   | 4 weeks  | alpine | 1.9 | 1.9         |
| php        | docker://bblfsh/php-driver:latest        | dev-087305b | beta   | 4 weeks  | alpine | 1.9 | 7.1.15-r0   |
+------------+------------------------------------------+-------------+--------+----------+--------+-----+-------------+
Response time 1.356628ms
```

I detected that the problem comes because of the capitalized `language`, it seems that bblfshd drivers are found by lower case names and it doesn't normalize the language before look for the driver.

If you run the test `TestUAST` it works properly, but if you change those cases using as language `python` to `Python`, it raised the same error in the bblfsh server:
```
docker run --rm --name bblfshd --privileged -p 9432:9432 -v /var/lib/bblfshd:/var/lib/bblfshd bblfsh/bblfshd:v2.4.2
time="2018-04-17T13:16:34Z" level=info msg="bblfshd version: v2.4.2 (build: 2018-03-13T15:34:28+0000)"
time="2018-04-17T13:16:34Z" level=info msg="initializing runtime at /var/lib/bblfshd"
time="2018-04-17T13:16:34Z" level=info msg="server listening in 0.0.0.0:9432 (tcp)"
time="2018-04-17T13:16:34Z" level=info msg="control server listening in /var/run/bblfshctl.sock (unix)"
time="2018-04-17T13:16:39Z" level=info msg="python-driver version: dev-5df023e (build: 2017-10-09T15:11:24Z)" id=01cb9w011jkrkt8yt7tvyr6dq6 language=python
time="2018-04-17T13:16:39Z" level=info msg="server listening in /tmp/rpc.sock (unix)" id=01cb9w011jkrkt8yt7tvyr6dq6 language=python
time="2018-04-17T13:16:40Z" level=info msg="new driver instance started bblfsh/python-driver:latest (01cb9w011jkrkt8yt7tvyr6dq6)"
time="2018-04-17T13:16:40Z" level=error msg="error selecting pool: could not autodetect language"
time="2018-04-17T13:16:40Z" level=error msg="request processed content 71 bytes, status Fatal" elapsed=75.208µs filename= language=
time="2018-04-17T13:16:40Z" level=error msg="error selecting pool: unexpected error: runtime failure: missing driver for language "Python""
time="2018-04-17T13:16:40Z" level=error msg="request processed content 71 bytes, status Fatal" elapsed=962.167µs filename= language=Python
time="2018-04-17T13:16:40Z" level=error msg="error selecting pool: unexpected error: runtime failure: missing driver for language "Python""
time="2018-04-17T13:16:40Z" level=error msg="request processed content 71 bytes, status Fatal" elapsed=807.451µs filename= language=Python

```

### PR DESCRIPTION
**Pull request by erizocosmico**
Fixes #240

### CODE REVIEW

File: internal/function/uast.go [hunk 1]
```diff
@@ -155,7 +155,7 @@ func (f UAST) Eval(ctx *sql.Context, row sql.Row) (interface{}, error) {
 			return nil, err
 		}
 
-		lang = lng.(string)
+		lang = strings.ToLower(lng.(string))
```
Comment (mcarmonaa) [inline internal/function/uast.go]: Should we handle this? or should we let LA know that bblfsh doesn't look for the driver properly because of a capitalization issue? It should work with the outcome enry is producing without any manipulation, right?

Comment (erizocosmico) [reply internal/function/uast.go]: That's assuming bblfsh wants to keep the same names Enry returns. @ajnavarro what do you think?
