### PR TITLE
internal/rule: fix indexes of filters in squash

### LINKED ISSUE #359: Wrong column accessed as YEAR function argument
The default gitbase-playground query does not work with v0.14.0-rc1.

```sql
SELECT COUNT(*) as num_commits, month, repo_id, committer_name
FROM ( SELECT MONTH(committer_when) as month,
              r.repository_id as repo_id,
              committer_name
    FROM ref_commits r
    INNER JOIN commits c
        ON YEAR(c.committer_when) = 2018 AND r.commit_hash = c.commit_hash
    WHERE r.ref_name = 'HEAD'
) as t GROUP BY committer_name, month, repo_id
```
```
ERROR 1105 (HY000): unknown error: value "...@gmail.com" can't be converted to time.Time: parsing time "...@gmail.com" as "2006-01-02": cannot parse "...@gmail.com" as "2006"
```

It looks like an off by 1 access to the row in `YEAR`. If you replace `YEAR(c.committer_when)` with the next column, `commit_message`, it works:

```sql
SELECT COUNT(*) as num_commits, month, repo_id, committer_name
FROM ( SELECT MONTH(committer_when) as month,
              r.repository_id as repo_id,
              committer_name
    FROM ref_commits r
    INNER JOIN commits c
        ON YEAR(c.commit_message) = 2018 AND r.commit_hash = c.commit_hash
    WHERE r.ref_name = 'HEAD'
) as t GROUP BY committer_name, month, repo_id
```

### PR DESCRIPTION
**Pull request by erizocosmico**
Fixes #359

### CODE REVIEW

File: internal/rule/squashjoins_test.go [hunk 1]
```diff
@@ -96,6 +96,17 @@ func TestSquashJoins(t *testing.T) {
 
 	result, err := SquashJoins(sql.NewEmptyContext(), analyzer.NewDefault(nil), node)
 	require.NoError(err)
+	result, err = result.TransformUp(func(n sql.Node) (sql.Node, error) {
+		fmt.Printf("%T\n", n)
```
Comment (ajnavarro) [inline internal/rule/squashjoins_test.go]: leftover?

Comment (erizocosmico) [reply internal/rule/squashjoins_test.go]: yup

Comment (erizocosmico) [reply internal/rule/squashjoins_test.go]: Fixed
